// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  ignite: require('../Images/ignite_logo.png'),
  tile_bg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  roses: require('../Images/roses.jpg'),
  bachelorette: require('../Images/bacheloretteTitle.png'),
  bachelor: require('../Images/bachelorTitle.png'),
  jojo: require('../Images/jojo.jpg'),
  cont1: require('../Images/contOne.jpg'),
  cont2: require('../Images/contTwo.jpg'),
  cont3: require('../Images/contThree.jpg'),
  cont4: require('../Images/contFour.jpg'),
  cont5: require('../Images/contFive.jpg'),
  cont6: require('../Images/contSix.jpg'),
  cont7: require('../Images/contSeven.jpg'),
  cont8: require('../Images/contEight.jpg'),
  cont9: require('../Images/contNine.jpg'),
  cont10: require('../Images/contTen.jpg'),
  cont11: require('../Images/contEleven.jpg'),
  cont12: require('../Images/contTwelve.jpg'),
  cont13: require('../Images/contThirteen.jpg'),
  cont14: require('../Images/contFourteen.jpg'),
  cont15: require('../Images/contFifteen.jpg'),
  cont16: require('../Images/contSixteen.jpg'),
  cont17: require('../Images/contSeventeen.jpg'),
  cont18: require('../Images/contEighteen.jpg'),
  cont19: require('../Images/contNineteen.jpg'),
  cont20: require('../Images/contTwenty.jpg'),
  cont21: require('../Images/contTwentyone.jpg'),
  cont22: require('../Images/contTwentytwo.jpg'),
  cont23: require('../Images/contTwentythree.jpg'),
  cont24: require('../Images/contTwentyfour.jpg'),
  cont25: require('../Images/contTwentyfive.jpg'),
  cont26: require('../Images/contTwentysix.jpg'),
}

export default images
